### ISSUE TITLE
Test datatables plugin

### ISSUE THREAD

**Issue by lguerin** [exanpe/exa-grails-plugins#2]

**Comment by jmaupoux** [comment]
## INTRO

Add a reference to datatables.net in Introduction

## USAGE

Show the json expected by the client, and the one used according to the example.

## FEATURES

For now, the datatables implementation preload all lines that's it ? It's an important information for an integration decision.

## TEST IN APP
- Ok for basic rendering
- With bootstrap, sort icons are not rendered. Should I declare bootstrap plugin ?
- I find it quite complicated to customize a column rendering, because this is the number 1 feature every table will leverage.
  Could we inject by default in datatables some js functions on a naming convention ? if js function declared, rendering is customized, otherwise not. User then only have to declare its custom function.

**Comment by lguerin** [comment]
Everything has been updated. 
Is the plugin ready to be published for you?

**Comment by jmaupoux** [comment]
I'm ok !
